### PR TITLE
Change 'Roles and teams' to 'Open positions'

### LINKED ISSUE #238: Change "Roles and teams" page title to "Open positions"
Since this page no longer describes the different teams, but is rather the listing of open positions, as a user I would like to more easily find that in the navigation.

### PR DESCRIPTION
**Pull request by fureigh**
This pull request clarifies (in the navigation and elsewhere) that the page formerly known as 'Roles and teams' actually lists 'Open positions'.

It also includes a redirect from `/roles-and-teams/`. If/when the 'Roles and teams' page is revived in #248, remove this redirect.

Closes #238.

### CODE REVIEW

**Comment by quepol** [comment]
:raised_hands: thanks!

**Comment by pixelwake** [comment]
Update makes prefect sense given how our process has evolved. Changes look good, I'll merge.

**Comment by pixelwake** [comment]
Reverted the merge in #252 per #251. I merged the PR for reverting due to this link being highly used by the 18F and it being highly visible to the public.  

@fureigh I don't know how to "re-open" this pr so that the redirect changes can be looked at and corrected.

**Comment by fureigh** [comment]
@rooneywp There's no way to reopen a pull request, only an issue. I'll pick it up in #251... had tested locally before submitting this pull request but I'll verify on staging before resubmitting.

**Comment by fureigh** [comment]
Confirming; fixed in cf63e68b8bbb51acc2e4173bb0b7d327775021d0.

**Pull request merged**
