### PR TITLE
Update open-positions.md

### PR DESCRIPTION
**Pull request by JennMoran**
Removed "We're briefly pausing applications while we evolve how 18F plans for open roles. Three positions remain open during this time" AND "If you’re interested in otherwise joining the team, please leave your name and email below and we'll let you know when we're hiring again. If you want to know more about what it’s like to be part of 18F, please send a note to <a href="mailto:join18f@gsa.gov">join18f@gsa.gov</a>." ALSO removed mailchimp sign up form.
Replaced it with: "The positions that we currently have available at 18F are posted here. These positions utilize a direct hiring authority. This differs slightly from the usual 18F process listed on our site but our talent team staff will guide you through the process. 
These are the only roles that we are hiring for; as new roles come available they will be listed here."

### CODE REVIEW

**Comment by fureigh** [comment]
Thanks @JennMoran!

Capturing the conversation we just had: it sounds like the Mailchimp list is being phased out, but it's still important that prospective applicants have a way to register their interest and find out when new roles open, so we'll keep the email information.

I'll update this pull request accordingly.

**Comment by fureigh** [comment]
Made a few small changes — @rooneywp, do you have bandwidth to take a look? (cc @JennMoran)

**Comment by JennMoran** [comment]
Thanks @fureigh yes we can keep the following: If you want to know more about what it’s like to be part of 18F, please send a note to join18f@gsa.gov

**Comment by fureigh** [comment]
Ah, thanks @JennMoran! I changed it to this:

> If you’re interested in otherwise joining the team, please send a note to <a href="mailto:join18f@gsa.gov">join18f@gsa.gov</a> and we'll let you know when new roles open up.

Is that accurate or should I ~~cut `and we'll let you know when new roles open up.`~~ change it to what you wrote?

**Comment by JennMoran** [comment]
we should cut "and we'll let you know when new roles open up".

**Comment by fureigh** [comment]
Will do. What's the best way for prospective applicants to find out when new roles open up? The 18F newsletter?

**Comment by JennMoran** [comment]
Yes  - when we do have a new role(s) we plan to announce it in the newsletter, otherwise people can just periodically check on our site

**Comment by JennMoran** [comment]
Maybe we should add: "If you are interested, you can sign-up to receive the 18F Newsletter which is sent out every two weeks and has information about 18F in general but will also includes updates specific to our hiring needs." and include the link there.  Thoughts @rooneywp

**Comment by fureigh** [comment]
How about this?

> If you'd like, you can sign up for the biweekly [18F Newsletter](https://18f.gsa.gov/#newsletter), which also includes updates about open roles.

**Comment by JennMoran** [comment]
Yes @fureigh let's go with that! 

I'm still not 100% with the wording on emailing us at join18F.  Thoughts @rooneywp ?

**Comment by pixelwake** [comment]
@JennMoran I agree. Although I see  the need to have a way for people to connect with someone on the talent team, I'm not clear on if the way we are messaging and using the join email is really effective or provides a great ux.

We may inadvertently be giving people false hope about getting a job here (since many people are emailing and expressing interest in a job) and since we don't have a clear way of managing the list, we are very likely providing an inconsistent candidate experience. Maybe it's not having a huge negative impact but at the very least, its a missed opportunity to delight.

I think is a pretty big opportunity area for us and if you are up for it, I think it needs some product management thinking. Until we have done the due diligence, we could leave the messaging is.

@fureigh Since we are updating the messaging, we could go back to using the API to push the links. Is that a trivial change?

**Comment by JennMoran** [comment]
@fureigh join18f- open positions link is displaying a 404

**Comment by fureigh** [comment]
@JennMoran Did #297 fix [this](https://github.com/18F/joining-18f/pull/296#issuecomment-233950329)?

**Comment by fureigh** [comment]
@rooneywp Re: using the API: you mean pulling the open positions from Lever, right? Provided the positions are marked correctly in Lever, that's quick to do.

What's the overall goal of this pull request/what problems does it seek to solve?

**Comment by fureigh** [comment]
@rooneywp @JennMoran It sounds like members of the talent team may not currently have bandwidth to respond to all emails to join18f@gsa.gov. If that's the case, is it feasible to systematize posting hiring updates to the Mailchimp list? Seems to be a simpler, less time-intensive, more consistent way to maximize the chances that applicants hear about open positions while still managing expectations. (If this is already the case, pardon.)

**Comment by JennMoran** [comment]
I think having them join the newsletter is the best way for them to hear about open positions.  The newsletter comes out every two weeks and we will let everyone know when a new role is open then.

**Comment by pixelwake** [comment]
@fureigh Re: API - I'll open a new issue for the so we don't confuse the two here as this was intended to just address the language on the site.

Re: the content update. We are just beginning to explore the efficacy and value of joining18F email and how it's managed, so we can withhold judgment on that. In the meantime, I agree with @JennMoran that if people want to be see updates to hiring without visiting the site, they should sign up for the newsletter. We are just going to hitch our content to their release train.

We can still leave the join18F on the page for now, we just don't want to set the expectation that its a way to "apply" without actually applying. It should be used for troubleshooting related stuff. 

If we offer signing up to the newsletter for updates then follow up with something like "If you need help understanding how to apply to 18F, please send your questions to join18F.gov." (An attempt to show that it's for customer support and not for application)

Thoughts?

**Comment by hestherchang** [comment]
+1 @rooneywp

**Comment by amandaschonfeld** [comment]
+1 @rooneywp

**Comment by fureigh** [comment]
@rooneywp Sounds good! I added some language about the newsletter yesterday; can you take a look at the most recent version and update it to reflect the language you suggested (re: customer service)?

**Pull request merged**
