### PR TITLE
Add application link as Markdown include

### LINKED ISSUE #241: Abstract application link to an include file
Context: #240

One possible direction: http://wolfslittlestore.be/2013/10/rendering-markdown-in-jekyll/

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #241.

Also takes care of the language mentioned in #240.

@fureigh this seemed to build and work just fine in Jekyll on my local system -- no problem rendering the markdown in the final build. I think it might be worth giving it a shot.

### CODE REVIEW

**Comment by fureigh** [comment]
@SeanKilleen Thanks for running with this! :rocket:

Will you rename `ApplyLink.md` to `apply-link.md` for the sake of consistency? I've followed up on the questions that are holding up the merge of those other two PRs, so hope to have answers (and merge this) today or tomorrow.

**Comment by SeanKilleen** [comment]
:+1: no problem -- fixed now. Let me know when it's ready to go and I'll squash it if you want.

**Comment by fureigh** [comment]
Looks good, @seankilleen, thanks! Now that #240 is merged there's a conflict, but I can sort that out and merge this.

**Comment by SeanKilleen** [comment]
@fureigh OK, let me know if you want me to take care of the conflict and I'll work through it. It can't be too major, likely just a language change, right? Happy to jump in again if you're strapped for time but I'll consider it done unless I hear back.

**Comment by fureigh** [comment]
Thanks, @SeanKilleen! If you have time that'd be fantastic.

**Comment by SeanKilleen** [comment]
@fureigh will do! Probably won't get to touch it until the weekend though.

**Comment by SeanKilleen** [comment]
@fureigh resolved! I'm going to try to squash and force push now.

**Comment by SeanKilleen** [comment]
@fureigh ...actually, at the risk of screwing things up with the merge, I'll leave the squashing to you.

**Comment by fureigh** [comment]
@SeanKilleen Sounds good, will do. Thanks for taking the additional time with it!

**Comment by fureigh** [comment]
Looks good. Merging! Thanks again, @SeanKilleen, and thanks for your patience on this one.

ping-pong-pigeons

**Pull request merged**
