### PR TITLE
Update salary links and examples for 2016

### PR DESCRIPTION
**Pull request by fureigh**
This PR addresses #244 and:
1. Updates example salary figures to reflect increases for 2016.
2. Updates year-specific "more information" links (the GS salary calculator and pay tables) to 2016 versions.

Sources for salary numbers:
- https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/salary-tables/16Tables/html/GS.aspx
- https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/2016/general-schedule-gs-salary-calculator/

**Outstanding question:**
What is "the annual **base** salary cap for all federal employees" in 2016? In 2015 it was $158,700.

### CODE REVIEW

**Comment by fureigh** [comment]
@rooneywp, can you find and update the "annual base salary cap for all federal employees" for 2016? See the "outstanding question" above. Thanks!

**Comment by pixelwake** [comment]
@fureigh Based on the 2016 tables the new maximum is 160,300. It might be confusing the way that we have it worded because the this max pay actually includes base+locality. We might want to consider changing the language around that number.

@cbrydges Can you validate this for us? For 2016 is the maximum GS pay 160,300 which includes both base and locality?

**Comment by fureigh** [comment]
@rooneywp I'll take out that sentence for now, for the sake of being able to correct the other outdated info that's still up. I'll merge this and stay tuned for @cbrydges' answer.

**Comment by cbrydges** [comment]
@rooneywp and @fureigh  Yes, $160,300 is the new maximum, no one can be offered more than that.  It is the base and locality pay in some areas like San Fran where you hit that maximum at a GS15 step 6, but in other areas like Kansas City a GS15 step 10 makes $152,780.  

Let me know if you have additional questions also here is a link to the 2016 pay tables 
https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/2016/general-schedule/

**Comment by fureigh** [comment]
@cbrydges Perfect, thanks for confirming!

**Comment by fureigh** [comment]
Closes #244.

**Comment by cbrydges** [comment]
@fureigh - I think I lead you astray - the base pay for a 15-10 without an locality pay is $133,444.  The link I provided above gives you access to the base table as well.  My apologies.

**Comment by fureigh** [comment]
@cbrydges Interesting — it was represented confusingly before, then, too. Good thing we're correcting it now! The page includes links to the salary calculator and that base table so all should now be clear. Thanks again.

**Pull request merged**
