### PR TITLE
Update text pay-grades.md

### PR DESCRIPTION
**Pull request by jtag**
That paragraph I suggested deleting need a bit more nuance, yes? 
1)Many people are joining from other areas of government, not just private industry
2)The idea of fresh troops b/c you will burn out might not be the best angle to include?
3)How to better articulate that we understand many work in many places over their career and four years is a reasonable 
4) Could emphasize these roles are not about being a career fed, but a term of service.
5) At the end of your term there could be opporunites to apply for other federal jobs in other agency digital services, other parts of GSA, etc. Correct?

^^^ I happened to be on the page (reviewing b/c a colleague is applying) and stumbled on this paragraph.

### CODE REVIEW

**Comment by fureigh** [comment]
@jtag Thanks for these changes!

It's my understanding that 5) is correct: our terms in these positions are not to exceed four years, but that doesn't mean we're limited to four years of service in the federal government, and there could very well be additional opportunities. Are you game to draft a sentence that incorporates that, or a paragraph that encapsulates the remaining points you raised?

**Comment by pixelwake** [comment]
:+1: To the changes.

**Comment by fureigh** [comment]
Swell. @jtag, do you have time to draft a sentence or a few that incorporates the info above? If not, we can merge this as-is and nudge someone else about that remaining piece.

**Comment by jtag** [comment]
Alas no bandwidth. So with it as you wish!

Jesse

On Tuesday, December 1, 2015, Fureigh notifications@github.com wrote:

> Swell. @jtag https://github.com/jtag, do you have time to draft a
> sentence or a few that incorporates the info above? If not, we can merge
> this as-is and nudge someone else about that remaining piece.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/joining-18f/pull/154#issuecomment-161133320.

## 

Jesse Taggert
Director of Experience Design & Product Strategy Practices
18F Consulting  | GSA
cell: 415-730-4965
_https://18f.gsa.gov/consulting/ https://18f.gsa.gov/consulting/_

**Comment by fureigh** [comment]
@jtag Thanks for the quick reply!

**Comment by fureigh** [comment]
@rooneywp, would you open an issue for this in the Writing Lab?

**Comment by pixelwake** [comment]
Submitted issue to writing lab 18F/writing-lab#139

**Comment by pixelwake** [comment]
I updated the PR with the copy edited by @kategarklavs.

@fureigh This is ready for review.

**Comment by fureigh** [comment]
@rooneywp @kategarklavs Thanks!

**Comment by fureigh** [comment]
I made two small edits I believe won't be controversial. If anyone was particularly attached to those parentheses, feel free to make another edit. :)

**Pull request merged**
