### PR TITLE
updateinterviewprocess.md

### PR DESCRIPTION
**Pull request by hestherchang**
remove "However, there is no limit to the number of times you can apply"

### CODE REVIEW

**Comment by fureigh** [comment]
@hestherchang Thanks for the pull request!

Has the process changed such that there is now a limit? If I recall correctly, this line was added to help reduce applicants' anxiety around GS level selection and the potential for thereby exacerbating gendered and other discrepancies in salaries.

**Comment by fureigh** [comment]
Updating to reflect conversation with @hestherchang: some applicants have repeatedly applied at the _same_ GS level and position, which is something we want to discourage, hence this pull request.

**Next step:** @hestherchang will draft alternate language that addresses both aims:
1. Reassure applicants that if their selected GS level doesn't work out, it won't reflect badly on them, and
2. Clarify that applications will be reviewed only once per GS level and position. (Per... some period of time, presumably.)

@hestherchang, if you'd like the Writing Lab to take a crack at that, @rooneywp is familiar with the process of calling them in and could likely walk you through it.

**Comment by pixelwake** [comment]
Just to make sure we are accurately gauging impact here, I did a bit of analysis to see how frequently applicants are applying to multiple roles (Both parallel and serial). Here are my findings.

image

From this it doesn't appear that the rate of re-application would cause significant increase in administrative burden. Philosophically then, I'm not sure it's it worth the risk of increased anxiety on not stating upfront that you can reapply as many times as you want, however small that risk might be. Most people are not abusing applications.

@hestherchang @fureigh Thoughts?

**Comment by fureigh** [comment]
@rooneywp Thanks for the analysis! The problem @hestherchang mentioned was people repeatedly applying for the _same_ role at the _same_ level, though. Are you able to run numbers on how many times that's happened?

Either way, I strongly suspect the potential costs of causing potential candidates more anxiety will outweigh the potential costs of processing the same person's application multiple times.

**Comment by pixelwake** [comment]
@fureigh Those numbers include people who apply to the same role multiple times and apply to different roles. So it's safe to assume that it's a even smaller percentage of applicants that would fall in that bucket only.

**Comment by coreycaitlin** [comment]
I think this issue is resolved (or at least significantly changed!) by the [new version of this guidance](https://18f.gsa.gov/join/#how-to-apply) on the 18F site. Closing this issue out for now — open a separate issue in the 18F site repo if you think this needs to be picked up again.

**Pull request closed without merging**
