### PR TITLE
Dynamically add Lever posts

### LINKED ISSUE #192: Reinstate dynamic generation of position listings
**Current behavior:**
This project is set up to dynamically generate position listings ([see a past example](https://github.com/18F/joining-18f/blob/6fffe4ddb5a1815ad8b62b886d328e20525582db/pages/who-we-are-hiring.md)) but we're currently hardcoding the list of open positions on the [roles and teams](https://github.com/18F/joining-18f/blob/18f-pages/pages/roles-and-teams.md) page. This risks mismatches between the positions' settings and their display and otherwise violates the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.

**Desired behavior:**
Positions are automatically listed based on the settings in their corresponding files.

**Technical notes:**
`{% include openpositions.html %}`

**Additional notes:**
- Verify first that the current position listing is accurate.
- Also verify that the format is consistent with what we need.

### PR DESCRIPTION
**Pull request by fureigh**
Fixes #192.

Still TODO:
- [x] Improve asset handling (see https://github.com/18F/guides-template/issues/69 for a possible workaround)
- [ ] Incorporate USWDS more thoroughly (corresponding ticket: #233)
- [ ] Remove vestigial elements from the previous approach. (I'll handle this in a separate PR. Corresponding ticket: #232)

### CODE REVIEW

**Comment by fureigh** [comment]
@rooneywp and @hestherchang, this is now up on staging: https://pages-staging.18f.gov/joining-18f/roles-and-teams/

I'm doing more around incorporating the U.S. Web Design Standards (and making this look better), but if you'd like me to go ahead and merge this so Lever posts show up in realtime Starting Now, let me know.

**Comment by fureigh** [comment]
Actually — with that last commit in, this is ready for review. I'll finesse the USWDS incorporation separately. Take a look when you get a chance.

**Comment by pixelwake** [comment]
@fureigh Fantastic! Tested the links and all is working for me. I also published a job from Lever to test the push through the API (pic below). All good! Merge when you are ready.

image

**Comment by fureigh** [comment]
@rooneywp Great! Thanks for testing and including that screenshot. Merging.

**Pull request merged**
