### PR TITLE
Update how-to-apply.md

### PR DESCRIPTION
**Pull request by elainekamlley**
Changed up the language to include two ways of to apply, directly with 18F and USDS. This addresses #12

@jamiealbrecht take a look and provide any feedback or merge the PR. Thanks!

### CODE REVIEW

**Comment by NoahKunin** [comment]
@elainekamlley Looks good to me with my correction on WH vs OMB org structure. Did @JenTress already :+1:? If so, I can merge.

**Comment by NoahKunin** [comment]
@JenTress approves per Slack, merging.

**Comment by jamiealbrecht** [comment]
I changed the language to take out the "including 18F" per @aaronsnow 's message in slack. cool? Hopefully didn't break the github.

**Comment by NoahKunin** [comment]
@jamiealbrecht omg, literal commit collisions, it's like crossing the streams in Ghostbusters all over again.

**Comment by JenTress** [comment]
Thank you both!

**Pull request merged**
