### PR TITLE
Update Apply link on how to apply

### PR DESCRIPTION
**Pull request by pixelwake**
Update the apply link to direct to the roles and teams page where links to the applications for each specific role are housed.

To #189

### CODE REVIEW

**Comment by fureigh** [comment]
Looks good to me! Holding off on merge until Lever-hosted applications are in place. (See milestone or #189 for further context.)

**Comment by fureigh** [comment]
@rooneywp Upon further review: the link text `Apply to join 18F` suggests that clicking it will lead immediately to an application, which is no longer the case. Users may be disoriented (and miss the application path) when they see the Roles and Teams page unless set up to expect that.

How about `Review current roles and apply to join 18F` instead?

**Comment by pixelwake** [comment]
@fureigh Makes sense. I will make the change here and on #204

**Comment by fureigh** [comment]
:tada:

**Pull request merged**
