### PR TITLE
Clarify annual leave total

### PR DESCRIPTION
**Pull request by pburkholder**
I think 4 hours/pay_period \* 26 pay_periods/year = 104 hours or 13 working days per year. Is that right?

### CODE REVIEW

**Comment by fureigh** [comment]
Good catch! That looks accurate to me — @rooneywp, can you confirm?

**Comment by fureigh** [comment]
(...confirm with HR, that is. @pburkholder's math is correct. :) )

**Comment by pburkholder** [comment]
Cool. Those 3 extra days matter IMHO....

**Comment by fureigh** [comment]
:) Agreed. Gonna go ahead and merge this one, ccing @cbrydges. Thanks again for the catch!

**Comment by pixelwake** [comment]
👍

**Pull request merged**
