### PR TITLE
Update hiatus language and add signup form

### PR DESCRIPTION
**Pull request by hestherchang**
trying to embed email form v2

### CODE REVIEW

**Comment by fureigh** [comment]
@hestherchang This has some conflicts with the main branch. I'm reviewing now and will pop this up on staging for review once that's set.

**Comment by fureigh** [comment]
I resolved those conflicts and made a few further changes.

@hestherchang, [take a look on staging](https://pages-staging.18f.gov/joining-18f/open-positions/) ([this page too](https://pages-staging.18f.gov/joining-18f/who-we-are-hiring/)) and merge if it looks good.

(ccing @rooneywp @msecret FYI)

**Comment by fureigh** [comment]
Merging per @hestherchang's go-ahead. Thanks, all!

**Comment by hestherchang** [comment]
thank you @fureigh  @msecret  for your wonderful dev skills, @rooneywp helping this morning, @jamiealbrecht  for the word crafting, @pkarman for helping with mailchimp. woohoo!

**Pull request merged**
