### PR TITLE
Remove hiring freeze notice, reinstate apply link

### LINKED ISSUE #103: Restore application link and remove hiring freeze notice

### PR DESCRIPTION
**Pull request by fureigh**
Reinstates copy from before 90022257d3f2a305eef85edc7002a7f8dbabc7b9. Closes #103.

### CODE REVIEW

**Comment by fureigh** [comment]
Please don't merge just yet; still verifying that the apply link works as expected.

**Comment by fureigh** [comment]
Should be good to go. @jamiealbrecht or @rooneywp, want to take a final look at this copy? I basically reinstated what was there before.

**Comment by jamiealbrecht** [comment]
I think we should change the last line to : If you want to be considered for the U.S. Digital Service family and other agencies — submit your application on the [USDS website](https://www.whitehouse.gov/digital/united-states-digital-service/apply). Enter "join18F" as the referral code.

**Comment by jamiealbrecht** [comment]
Also, not sure we need to talk about USDS on our apply as much. I am cool with leaving it at the end as another place. Not sure if we need to talk about 18F that way either in the beginning, maybe just link to the application? and our join18f@gsa.gov email if people have questions?

**Comment by fureigh** [comment]
@jamiealbrecht Remove the final sentence about it taking longer, then?

**Comment by fureigh** [comment]
I wish it were possible to do pull requests on pull requests. :)

**Comment by jamiealbrecht** [comment]
Yes! And yes, completely agree.

**Comment by jamiealbrecht** [comment]
wait can you do PRs on PRs? #n00b

**Comment by fureigh** [comment]
@jamiealbrecht It's not possible, AFAIK.

Question about removing that final sentence: is it no longer true? If it's still true, I think we should give people a heads-up before they make the decision about which way to apply.

**Comment by jamiealbrecht** [comment]
hahah :) 

I am not sure that their process takes longer anymore. Under this new process, it will most likely take around 5 weeks before we review all resumes in a cohort.  And I want to make it clear that people should no longer apply to USDS and expect to get routed to 18F. Hope that makes sense.

**Comment by fureigh** [comment]
@jamiealbrecht Oh! Okay. I removed that last sentence.

How about we merge this so the application's up for anyone who's looking and use a new PR to wordsmith the rest of how to talk about USDS?

**Comment by jamiealbrecht** [comment]
:+1:

**Comment by fureigh** [comment]
Thanks!

rocketsnail

**Pull request merged**
