### PR TITLE
Create Program Manager-Feedback Analytics.MD

### PR DESCRIPTION
**Pull request by rachellegupta**
Adding the file for the job descriptions to be added to the join18 page.

### CODE REVIEW

**Comment by rachellegupta** [comment]
@fureigh if the formatting is 👌 can you merge?

**Comment by fureigh** [comment]
Hi @rachellegupta!

Please:
- Change the filename to be all-lowercase and contain no spaces, consistent with the others in the `_positions` directory.
- Add the necessary metadata at the start of the file, consistent with the others in the `positions` directory. Without it, the page won't work properly.
- Update the copy to be consistent with 18F's [Content Guide](https://pages.18f.gov/content-guide/) (lowercase `federal` , etc.).
- Do another check for missing periods, etc.
- Remove trailing whitespace from the end of the file.

I also suggest adding:
- Location information,
- Clarification that this is not a position with 18F, and
- A link to the GS calculator.

I believe the other listed positions include relevant text that can be copied.

Once that's all set, let me know where you'd like the link to this to appear on the `Open Positions` page.

Thanks!

**Comment by fureigh** [comment]
...and if you have any questions about the above, feel free to ping me in Slack. :)

**Comment by JenTress** [comment]
@fureigh and @rachellegupta did a review and made changes suggested. We should have a title above HUD's roles saying "GSA Feedback Analytics Roles," and then the two positions will fall under.

With that, I _think_ we're good to go!

**Comment by rachellegupta** [comment]
I think we're good to merge now, thanks for your suggestions and your 👀 @fureigh

**Pull request merged**
