### PR TITLE
Updated resume section

### PR DESCRIPTION
**Pull request by hestherchang**
Issue #328

I wasn't sure how to add a PDF in the pull request. "This guide" in bold in the second paragraph should link to the pdf guide we created (and be unbolded). The PDF is in the issue #328  and I can also send it via email.  Thank you.

### CODE REVIEW

**Comment by fureigh** [comment]
@hestherchang Was that PDF created by 18F? If so, mind if I change its filename from `SkeletonGenericResumeFINAL.pdf` to something like `18F-SampleGovernmentResume.pdf`?

**Comment by fureigh** [comment]
@hestherchang Also, I got a little excited and made some copy edits directly to your branch — pardon. If you'd like me to revert them, let me know.

**Comment by hestherchang** [comment]
@fureigh  Yes, you may change the file name. How about "18F-GovernmentResumeGuide.pdf"? Yes, I am ok with your copy edits. Thank you.

**Comment by fureigh** [comment]
@hestherchang I'm verifying that the link to the PDF is set up correctly. We ought to also — or instead — include a link to a non-PDF version, though, for reasons of 508 compliance and otherwise.

Are you comfortable starting a new page and formatting that in markdown? You'd use the 'Create new file' button from within the `pages` folder.

**Comment by fureigh** [comment]
Hmm — I'm getting a 403 error when I try to access staging. The above question holds.

**Comment by hestherchang** [comment]
Saw the commits you made about 15mins ago. Looks good, thank you. 

Yes, I will try creating a non-pdf version in 'pages' folder. Will start it sometime today.

**Comment by fureigh** [comment]
@hestherchang Now that #331 is merged in, this should link to that instead of to the PDF, correct?

**Comment by hestherchang** [comment]
Sure, sounds like a great idea @fureigh

**Comment by fureigh** [comment]
Closing this one; please see #329, which includes all changes so far from here. (Switching to a new PR for the sake of expediency.)

**Pull request closed without merging**
