### PR TITLE
Swap in short position descriptions

### PR DESCRIPTION
**Pull request by fureigh**
Address #64 using phrasing drawn from https://18f.gsa.gov/2015/02/25/We-Are-Hiring/. Per #62 and conversation with @jamiealbrecht, this includes only positions for which 18F is actively hiring.

### CODE REVIEW

**Comment by fureigh** [comment]
@arowla, another option would have been to mark all current positions 'inactive' and add new positions in `_positions` corresponding to these new descriptions. I took this approach instead because the descriptions are so much shorter it seemed clearer to just display them all on this same page. What do you think?

**Comment by fureigh** [comment]
Got the go-ahead on content, so merging this for now. Will reopen if there's further discussion about how best to have implemented this.

**Comment by arowla** [comment]
LGTM!

**Comment by fureigh** [comment]
@arowla Thanks!

**Pull request merged**
