### PR TITLE
Application and Int process upd

### PR DESCRIPTION
**Pull request by pixelwake**
To #143

Drafted up some language to start describing some of the more granular, policy oriented requirements/details about our process.

### CODE REVIEW

**Comment by pixelwake** [comment]
Created issue for the copy edit on 18F/writing-lab#66

**Comment by fureigh** [comment]
:+1:

**Comment by fureigh** [comment]
@rooneywp Merged a PR from @awfrancisco before noticing it was against this branch — pardon. Is this ready to be merged?

**Comment by pixelwake** [comment]
@fureigh No worries, this PR is ready to go. With Andre's edits I think it's ready to merge. Do you want to take one more look and merge if you agree?

**Pull request merged**
