### PR TITLE
point people to USDS

### PR DESCRIPTION
**Pull request by afeld**
Worth giving people this extra option, especially while our application process is frozen.

### CODE REVIEW

**Comment by fureigh** [comment]
@afeld Thanks for the PR! I hope you don't mind that I piggybacked on it. Take a look and let me know it still works for you.

(@jamiealbrecht, any reason not to re-include USDS at this time?)

**Comment by afeld** [comment]
:+1:

**Comment by jamiealbrecht** [comment]
I am game with pointing people to USDS for sure. However, I think the wording should be slightly different. We (will be) hiring a lot of the exact same skill sets.

Perhaps something like, "We encourage you to also consider applying to the US Digital Service." Or something similar? @fureigh you're good with words, thoughts?

**Comment by fureigh** [comment]
Here are a few possibilities:
1. We encourage you to also consider applying to the [U.S. Digital Service](https://www.whitehouse.gov/digital/united-states-digital-service), which is hiring more broadly.
2. You may also want to check out the [U.S. Digital Service](https://www.whitehouse.gov/digital/united-states-digital-service), which is hiring more broadly.
3. [Either of the above starts, then] the [U.S. Digital Service](https://www.whitehouse.gov/digital/united-states-digital-service), which includes opportunities at a broader range of agencies.
4. [Either of the above starts, then] the [U.S. Digital Service](https://www.whitehouse.gov/digital/united-states-digital-service).

Which do you prefer? Leaving "which is hiring more broadly" in does give the impression that that's the primary distinction, which isn't accurate.

**Comment by jamiealbrecht** [comment]
Maybe something like this?... We encourage you to also consider applying to the U.S. Digital Service, which includes opportunities at a broader range of agencies.

**Comment by fureigh** [comment]
Sounds good to me. @afeld?

**Comment by afeld** [comment]
:+1:

**Pull request merged**
