### PR TITLE
Finish #328

### PR DESCRIPTION
**Pull request by fureigh**
Includes changes from #329.

### CODE REVIEW

**Comment by fureigh** [comment]
@hestherchang Ready for review.

**Comment by hestherchang** [comment]
(how do i review this?) @fureigh

**Comment by fureigh** [comment]
@hestherchang Look through the `Files changed` tab and click on lines to add comments. Or if it all looks good to you, you're welcome to just say that. I'd offer to screenshare and pair on this but I'm booked for the rest of the day. Thanks for taking a look!

**Comment by hestherchang** [comment]
thank you! review complete - looks good to go. @fureigh

**Comment by fureigh** [comment]
high-five-fresh-prince

**Pull request merged**
