### PR TITLE
Created content designer file

### PR DESCRIPTION
**Pull request by pixelwake**
No actual file changes. I originally committed this file directly to see if it would work. I created this PR so that the file could be reviewed.

### CODE REVIEW

**Comment by fureigh** [comment]
@rooneywp Bill, with great power comes great responsibility! ;) The general principle I've been following is to make direct commits only when they're typo fixes that definitely don't require discussion. (Which, it should be noted, is not the case for all typo fixes.) I'm loving your "commit early and often" approach, though.

On that note, I committed a typo fix and some whitespace fixes here. A question here, as I can't post a line comment there: is `active` meant to be set to `false`?

**Comment by pixelwake** [comment]
@fureigh Yeah, I was impatient on this one :)

I left the active set to false because I'm not 100% certain what it does. It looks like there was a script/code in the _includes folder that uses that field to make automated changes to the site. I don't know if that function is getting called anywhere today but I figured I'd leave it to inactive to be on the safe side.

As a heads up I'll be creating/updating a number of the profiles using the the content that was created by the teams and run through the writing lab already. So hopefully there shouldn't be too many copy edits/typos that we'll have to make.

**Comment by fureigh** [comment]
@rooneywp Thanks for the heads-up! Sounds good.

The `active` field indicates whether the position is currently open (`true`) or inactive (`false`). If this position's meant to be open, please update accordingly. If it's not meant to be open, let me know and I'll merge this as-is.

**Comment by pixelwake** [comment]
@fureigh :+1: Let's leave it inactive.

**Comment by fureigh** [comment]
@rooneywp Merging, then. I'll await your forthcoming "open the floodgates" PR. :)

**Pull request merged**
