### PR TITLE
Remove RaaS roles

### PR DESCRIPTION
**Pull request by pixelwake**

### CODE REVIEW

**Comment by pixelwake** [comment]
@fureigh This is ready for review. PR to remove the content for RaaS postings and delete the associated files.

**Comment by fureigh** [comment]
@rooneywp Looks good to me!

high-five-cat

**Comment by fureigh** [comment]
@rooneywp One more question, though: can you confirm that the GSA roles were left intentionally? I ask because of the title of this pull request.

**Comment by pixelwake** [comment]
@fureigh Yes, I intentionally left those roles up. Thanks 👍

**Comment by fureigh** [comment]
@rooneywp 🆒  Thanks for confirming

**Pull request merged**
